PREFIX Test: <http://example.org/Test#>

SELECT ?name ?subject
WHERE
 { 
	?student Test:Name ?name .
	?taken Test:Taken-Student ?student .
	?taken Test:Taken-Classes ?class .
	?class Test:Subject ?subject .
	FILTER regex(?name, "^A")
}